[package]
name = "examples_support"
version = "0.0.1"
edition = "2021"

[dependencies]

async-channel = { version = "1.8.0" }
async-trait =   { workspace = true }
env_logger =    { workspace = true }
log =           { workspace = true }
strum =         { version = "0.24", features = ["derive"] }
thiserror =     { version = "1.0.31" }
time =          { version = "0.3.17" }
tokio =         { workspace = true, features = ["full"] }
uuid =          { version = "1.2.2", features = ["v4"] }
