[package]
name = "examples_support"
version = "0.0.1"
edition = "2021"

[dependencies]

cohort =        { path = "../cohort" }
metrics =       { path = "../metrics" }

# Postgres
refinery =          { version = "0.8.7", features = ["tokio-postgres"] }
tokio-postgres =    { version = "0.7", features = [ "with-uuid-1", "with-serde_json-1" ] }
deadpool-postgres = { version = "0.10" }

async-channel = { version = "1.8.0" }
async-trait =   { workspace = true }
env_logger =    { workspace = true }
log =           { workspace = true }
strum =         { version = "0.24", features = ["derive"] }
rust_decimal =  { version = "1.30.0", features = ["db-tokio-postgres", "serde-with-float"] }
thiserror =     { version = "1.0.31" }
time =          { version = "0.3.17" }
tokio =         { workspace = true, features = ["full"] }
uuid =          { version = "1.2.2", features = ["v4"] }
