[package]
name = "talos_common_utils"
version = "0.2.20-dev"
edition = "2021"
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Common utilities used in Talos"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging
log = { workspace = true }
env_logger = { workspace = true }

[dev-dependencies]
serial_test = "2.0.0"
