[package]
name = "talos_common_utils"
version = "0.2.53-dev"
edition = "2021"
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Common utilities used in Talos"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { version = "0.28.0", default-features = false, features = [
    "trace",
] }

tokio = { workspace = true, features = ["full"] }
# Time
time = { version = "0.3.17" }

[dev-dependencies]
serial_test = "2.0.0"
