[package]
name = "talos_common_utils"
version = "0.2.60-dev"
edition = "2021"
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Common utilities used in Talos"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

opentelemetry_api =         { version = "0.20.0", features = ["metrics"] }
opentelemetry =             { version = "0.28.0", default-features = false, features = ["trace"]  }
opentelemetry_sdk =         { version = "0.28.0", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-otlp =        { version = "0.28.0", features = [ "trace", "grpc-tonic" ] }
opentelemetry-stdout =      { version = "0.28.0", features = [ "trace" ] }

tracing =                   { version = "0.1.41", features = [ "log" ] }
tracing-opentelemetry =     { version = "0.29.0" }
tracing-bunyan-formatter =  { version = "0.3.10" }
tracing-subscriber =        { version = "0.3.19", features = [ "fmt", "ansi", "json", "registry", "env-filter" ] }

strum = { version = "0.27.1", features = ["derive"] }
thiserror = { version = "2.0.11" }
tokio = { workspace = true, features = ["full"] }
time = { version = "0.3.17" }

[dev-dependencies]
serial_test = "2.0.0"
