[package]
name = "metrics"
version = "0.2.3-dev"
edition = "2021"

[dependencies]

once_cell =                 { version = "1.18.0"}
opentelemetry_api =         { version = "0.20.0", features = ["metrics"] }
opentelemetry-stdout =      { version = "0.1.0", features = ["metrics"] }
opentelemetry_sdk =         { version = "0.20.0", features = ["metrics", "rt-tokio"] }
opentelemetry  =            { version = "0.20.0", features = ["metrics"] }

serde =                     { workspace = true }
serde_json =                { workspace = true }

env_logger =                { workspace = true }
log =                       { workspace = true }

time =                      { version = "0.3.17" }
