[package]
name = "talos_rdkafka_utils"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
talos_common_utils = { path = "../talos_common_utils" }
# Logging
log = { workspace = true }
env_logger = { workspace = true }

# Test
mockall = "0.11.0"

# Error
thiserror = "1.0.31"

rdkafka = { version = "0.34.0", features = ["sasl"] }
rdkafka-sys = { version = "4.6.0", features = ["ssl-vendored", "gssapi-vendored"] }
openssl-sys = { version = "0.9", features = ["vendored"] }
openssl = { version = "0.10", features = ["vendored"] }

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.5.1"
serial_test = "2.0.0"