[package]
name = "talos_metrics"
version = "0.2.52-dev"
edition = "2021"
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Metric utilities used in Talos"

[dependencies]

once_cell =                 { version = "1.18.0"}
opentelemetry_api =         { version = "0.20.0", features = ["metrics"] }
opentelemetry-stdout =      { version = "0.1.0", features = ["metrics"] }
opentelemetry_sdk =         { version = "0.20.0", features = ["metrics", "rt-tokio"] }
opentelemetry  =            { version = "0.20.0", features = ["metrics"] }

serde =                     { workspace = true }
serde_json =                { workspace = true }

env_logger =                { workspace = true }
log =                       { workspace = true }

time =                      { version = "0.3.17" }
