[package]
name = "banking_replicator"
version = "0.2.35-dev"
edition = "2021"

[dependencies]
async-trait =       { workspace = true }
env_logger =        { workspace = true }
log =               { workspace = true }
serde =             { workspace = true }
serde_json =        { workspace = true }
tokio =             { workspace = true, features = ["full"] }

# Postgres
refinery =          { version = "0.8.7", features = ["tokio-postgres"] }
rust_decimal =      { version = "1.30.0", features = ["db-tokio-postgres", "serde-with-float"] }
tokio-postgres =    { version = "0.7", features = [ "with-uuid-1", "with-serde_json-1" ] }
deadpool =          { version = "0.10.0" }
deadpool-postgres = { version = "0.11.0" }

futures =           { version = "0.3.28" }
opentelemetry_api = { version = "0.20.0" }
opentelemetry_sdk = { version = "0.20.0", features = ["metrics", "rt-tokio"] }
opentelemetry =     { version = "0.20.0" }
strum =             { version = "0.25", features = ["derive"] }
uuid =              { version = "1.4.1", features = ["v4"] }

banking_common =            { path = "../banking_common", version = "0.2.35-dev" }
cohort_sdk =                { path = "../cohort_sdk", version = "0.2.35-dev" }
talos_metrics =             { path = "../talos_metrics", version = "0.2.35-dev" }
talos_cohort_replicator =   { path = "../talos_cohort_replicator", version = "0.2.35-dev" }
talos_rdkafka_utils =       { path = "../talos_rdkafka_utils", version = "0.2.35-dev" }
talos_certifier =           { path = "../talos_certifier", version = "0.2.35-dev" }
talos_certifier_adapters =  { path = "../talos_certifier_adapters", version = "0.2.35-dev" }
