[package]
name = "cohort_sdk"
version = "0.0.1"
edition = "2021"

[dependencies]

async-trait =               { workspace = true }
cohort =                    { path = "../cohort" }
env_logger =                { workspace = true }
log =                       { workspace = true }
futures =                   { version = "0.3.28" }
rdkafka =                   { version = "0.33.0", features = ["sasl"] }
rdkafka-sys =               { version = "4.3.0" }
serde =                     { workspace = true }
serde_json =                { workspace = true }
talos_agent =               { path = "../talos_agent" }
talos_suffix =              { path = "../talos_suffix" }
talos_certifier =           { path = "../talos_certifier" }
talos_certifier_adapters =  { path = "../talos_certifier_adapters" }

tokio =                     { workspace = true, features = ["full"] }