[package]
name = "cohort_sdk"
version = "0.2.16"
edition = "2021"

[dependencies]

async-trait = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
futures = { version = "0.3.28" }
opentelemetry_api = { version = "0.20.0" }
opentelemetry_sdk = { version = "0.20.0", features = ["metrics", "rt-tokio"] }
opentelemetry = { version = "0.20.0" }
rand = { version = "0.8.5" }

rdkafka = { version = "0.34.0", features = ["sasl"]  }

serde = { workspace = true }
serde_json = { workspace = true }
strum = { version = "0.25", features = ["derive"] }
talos_metrics =             { path = "../talos_metrics", version = "0.2.16" }
talos_agent =               { path = "../talos_agent", version = "0.2.16" }
talos_certifier =           { path = "../talos_certifier", version = "0.2.16" }
talos_cohort_replicator =   { path = "../talos_cohort_replicator", version = "0.2.16" }
talos_rdkafka_utils =       { path = "../talos_rdkafka_utils", version = "0.2.16" }
uuid =                      { version = "1.4.1", features = ["v4"] }

tokio = { workspace = true, features = ["full"] }
