[package]
name = "logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
# Logging
log = { workspace = true }
env_logger = { workspace = true }

# Error
thiserror = "1.0.31"

# Date Time
chrono = { version = "0.4", features = ["serde"] }
