[package]
name = "talos_certifier"
version = "0.2.54-dev"
edition = "2021"
keywords = ["talos"]
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Talos is based on the STRIDE algorithm for strict serializable certification of distributed transactions"

[dependencies]
#
strum = { version = "0.24", features = ["derive"] }

#  Ahash hashmap
ahash = "0.8.3"

# Logging
log = { workspace = true }
env_logger = { workspace = true }

# Async
tokio = { workspace = true }
futures-util = "0.3.26"
async-trait = { workspace = true }

# Json Serialize / Deserialize
serde = { workspace = true }
serde_json = { workspace = true }

time = { version = "0.3.30", features = ["formatting"] }

# Error
thiserror = "1.0.31"

opentelemetry_api =         { version = "0.20.0", features = ["metrics"] }
opentelemetry =             { version = "0.28.0", default-features = false, features = ["trace"]  }
opentelemetry_sdk =         { version = "0.28.0", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-otlp =        { version = "0.28.0", features = [ "trace", "grpc-tonic" ] }
opentelemetry-stdout =      { version = "0.28.0", features = [ "trace" ] }

tracing =                   { version = "0.1.41", features = [ "log" ] }
tracing-opentelemetry =     { version = "0.29.0" }
tracing-bunyan-formatter =  { version = "0.3.10" }
tracing-subscriber =        { version = "0.3.19", features = [ "fmt", "ansi", "json", "registry", "env-filter" ] }

# internal crates
talos_suffix = { path = "../talos_suffix", version = "0.2.54-dev" }
talos_common_utils = { path = "../talos_common_utils", version = "0.2.54-dev" }

uuid = { version = "1.4.1", features = ["v4"] }

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.4"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false  # Disable features which are enabled by default
features = ["user-hooks"]


[[bench]]
name = "certifier"
harness = false
