[package]
name = "talos_certifier"
version = "0.2.29"
edition = "2021"
keywords = ["talos"]
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Talos is based on the STRIDE algorithm for strict serializable certification of distributed transactions"

[dependencies]
#
strum = { version = "0.24", features = ["derive"] }

#  Ahash hashmap
ahash = "0.8.3"

# Logging
log = { workspace = true }
env_logger = { workspace = true }

# Async
tokio = { workspace = true }
futures-util = "0.3.26"
async-trait = { workspace = true }

# Json Serialize / Deserialize
serde = { workspace = true }
serde_json = { workspace = true }

time = { version = "0.3.30", features = ["formatting"]}

# Error
thiserror = "1.0.31"

# internal crates
talos_suffix = { path = "../talos_suffix", version = "0.2.29" }

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.4"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false  # Disable features which are enabled by default
features = ["user-hooks"]


[[bench]]
name = "certifier"
harness = false
