[package]
name = "talos_cohort_replicator"
version = "0.2.31-dev"
edition = "2021"

[lib]
doctest = false

[dependencies]
# Packages from workspace
async-trait =       { workspace = true }
env_logger =        { workspace = true }
log =               { workspace = true }
serde =             { workspace = true }
serde_json =        { workspace = true }
tokio =             { workspace = true, features = ["full"] }

strum =             { version = "0.25", features = ["derive"] }
# Error
thiserror =         { version = "1.0.31" }

# Time
time =              { version = "0.3.17" }

#  indexmap
indexmap = { version = "2.0.0", features = ["rayon"]}
ahash = "0.8.3"

talos_certifier =            { path = "../talos_certifier", version = "0.2.31-dev" }
talos_suffix =               { path = "../talos_suffix", version = "0.2.31-dev" }

[dev-dependencies]
mockall =       { version = "0.11.3" }
tokio-test =    { version = "0.4.2" }
rand =          { version = "0.8.5" }
