[package]
name = "cohort_banking"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait =       { workspace = true }
env_logger =        { workspace = true }
log =               { workspace = true }
serde =             { workspace = true }
serde_json =        { workspace = true }
tokio =             { workspace = true, features = ["full"] }

async-channel =     { version = "1.8.0" }
futures =           { version = "0.3.28" }
opentelemetry_api = { version = "0.20.0" }
opentelemetry_sdk = { version = "0.20.0", features = ["metrics", "rt-tokio"] }
opentelemetry =     { version = "0.20.0" }
rand =              { version = "0.8.5" }
strum =             { version = "0.25", features = ["derive"] }
uuid =              { version = "1.2.2", features = ["v4"] }

rust_decimal =      { version = "1.30.0", features = ["db-tokio-postgres", "serde-with-float"] }
tokio-postgres =    { version = "0.7", features = [ "with-uuid-1", "with-serde_json-1" ] }

cohort_sdk =                 { path = "../cohort_sdk" }
banking_common =             { path = "../banking_common" }
talos_agent =                { path = "../talos_agent" }
metrics =                    { path = "../metrics" }
talos_certifier =            { path = "../talos_certifier" }
talos_cohort_replicator =    { path = "../talos_cohort_replicator" }
talos_suffix =               { path = "../talos_suffix" }