[package]
name = "cohort_banking"
version = "0.3.11"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }

async-channel = { version = "1.8.0" }
futures = { version = "0.3.28" }
opentelemetry_api = { version = "0.20.0" }
opentelemetry_sdk = { version = "0.20.0", features = ["metrics", "rt-tokio"] }
opentelemetry = { version = "0.20.0" }
rand = { version = "0.8.5" }
refinery = { version = "0.8.7", features = ["tokio-postgres"] }
rust_decimal = { version = "1.30.0", features = [
    "db-tokio-postgres",
    "serde-with-float",
] }
strum = { version = "0.25", features = ["derive"] }
# TODO:GK pinned to version that supports MSRV 1.75. When we move our rust version to 1.81 or higher, we should relax this pin.
tokio-postgres = { version = "=0.7.13", features = [
    "with-uuid-1",
    "with-serde_json-1",
] }
uuid = { version = "1.4.1", features = ["v4"] }

cohort_sdk = { path = "../cohort_sdk", version = "0.3.11" }
banking_common = { path = "../banking_common", version = "0.3.11" }
talos_agent = { path = "../talos_agent", version = "0.3.11" }
talos_metrics = { path = "../talos_metrics", version = "0.3.11" }
talos_certifier = { path = "../talos_certifier", version = "0.3.11" }
talos_cohort_replicator = { path = "../talos_cohort_replicator", version = "0.3.11" }
talos_common_utils = { path = "../talos_common_utils", version = "0.3.11" }
talos_suffix = { path = "../talos_suffix", version = "0.3.11" }
