[package]
name = "cohort"
version = "0.0.1"
edition = "2021"

[dependencies]

async-trait =   { workspace = true }
env_logger =    { workspace = true }
log =           { workspace = true }
multimap =      { version = "0.8.3" }
rdkafka =       { version = "0.29.0", features = ["sasl"] }
rdkafka-sys =   { version = "4.3.0" }
serde =         { workspace = true }
serde_json =    { workspace = true }
strum =         { version = "0.24", features = ["derive"] }
thiserror =     { version = "1.0.31" }
time =          { version = "0.3.17" }
tokio =         { workspace = true, features = ["full"] }
uuid =          { version = "1.2.2", features = ["v4"] }
rusty-money =   { version = "0.4.1" }
talos_agent =   { path = "../talos_agent" }
rand =          { version = "0.8.5" }

[dev-dependencies]
mockall =       { version = "0.11.3" }
tokio-test =    { version = "0.4.2" }
