[package]
name = "talos_services"
version = "0.1.0"
edition = "2021"

[dependencies]
# Logging
log = { workspace = true }
env_logger = { workspace = true }

# Async
tokio = { workspace = true, features = ["full", "test-util"] }
async-trait = { workspace = true }
futures-util = "0.3.21"

# Json Serialize / Deserialize
serde = { workspace = true }
serde_json = { workspace = true }

# Kafka
rdkafka = { version = "0.29.0", features = ["sasl"] }

# Error
thiserror = "1.0.31"

# internal crates
certifier = { path = "../certifier" }
suffix = { path = "../suffix" }
logger = { path = "../logger" }
talos_core = { path = "../talos_core" }
talos_adapters = { path = "../talos_adapters" }
