[package]
name = "talos_messenger_actions"
version = "0.2.1-dev"
edition = "2021"

[lib]
doctest = false

[dependencies]
# Packages from workspace
async-trait = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# Strum
strum = { version = "0.25", features = ["derive"] }

# Futures
futures-util = "0.3.26"
futures-executor = "0.3.28"

# Error
thiserror = { version = "1.0.31" }

# Kafka
rdkafka = { version = "0.34.0", features = ["sasl"] }

# Time
time = { version = "0.3.30" }

#  indexmap
indexmap = { version = "2.0.0", features = ["rayon"] }
ahash = "0.8.3"

talos_certifier = { path = "../talos_certifier", version = "0.2.1-dev" }
talos_certifier_adapters = { path = "../../packages/talos_certifier_adapters", version = "0.2.1-dev" }
talos_rdkafka_utils = { path = "../../packages/talos_rdkafka_utils", version = "0.2.1-dev" }
talos_messenger_core = { path = "../../packages/talos_messenger_core", version = "0.2.1-dev" }

[dev-dependencies]
mockall = { version = "0.11.3" }
tokio-test = { version = "0.4.2" }
rand = { version = "0.8.5" }
