[package]
# [package]
name = "talos_certifier_adapters"
version = "0.2.40"
edition = "2021"
keywords = ["talos", "adapters"]
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Adapters used in Talos Certifier"

[dependencies]

# Json Serialize / Deserialize
serde = { workspace = true }
serde_json = { workspace = true }

# Logging
log = { workspace = true }
env_logger = { workspace = true }
# Async
tokio = { workspace = true }
async-trait = { workspace = true }
futures-util = "0.3.21"
# Kafka
rdkafka = { version = "0.34.0", features = ["sasl"]  }

#  Ahash hashmap
ahash = "0.8.3"

# uuid
uuid = { version = "1.4.1", features = ["v4"] }
# postgres
tokio-postgres = { version = "0.7", features = [
    "with-uuid-1",
    "with-serde_json-1",
] }
deadpool-postgres = "0.11.0"
refinery = { version = "0.8.7", features = ["tokio-postgres"] }

time = { version = "0.3.30" }

# Error
thiserror = "1.0.31"

# Test
mockall = "0.11.0"

# internal crates
talos_metrics =       { path = "../talos_metrics", version = "0.2.40" }
talos_certifier =     { path = "../talos_certifier", version = "0.2.40" }
talos_suffix =        { path = "../talos_suffix", version = "0.2.40" }
talos_common_utils =  { path = "../talos_common_utils", version = "0.2.40" }
talos_rdkafka_utils = { path = "../talos_rdkafka_utils", version = "0.2.40" }


[dev-dependencies]
serial_test = "2.0.0"
