[package]
# [package]
name = "talos_certifier_adapters"
version = "0.0.1"
edition = "2021"
keywords = ["talos", "adapters"]
description = "Adapters used in Talos Certifier"

[dependencies]

# Json Serialize / Deserialize
serde = { workspace = true }
serde_json = { workspace = true }

# Logging
log = { workspace = true }
env_logger = { workspace = true }
# Async
tokio = { workspace = true }
async-trait = { workspace = true }
futures-util = "0.3.21"
# Kafka
rdkafka = { version = "0.34.0" }
#rdkafka-sys = { version = "4.6.0", features = ["ssl-vendored", "gssapi-vendored"] }
#openssl-sys = { version = "0.9", features = ["vendored"] }
#openssl = { version = "0.10", features = ["vendored", "v111"] }

# uuid
uuid = { version = "1.4.1", features = ["v4"] }
# postgres
tokio-postgres = { version = "0.7", features = [
    "with-uuid-1",
    "with-serde_json-1",
] }
deadpool-postgres = "0.11.0"
refinery = { version = "0.8.7", features = ["tokio-postgres"] }

time = { version = "0.3.17" }

# Error
thiserror = "1.0.31"

# Test
mockall = "0.11.0"

# internal crates
logger =              { path = "../logger" }
metrics =             { path = "../metrics" }
talos_certifier =     { path = "../talos_certifier" }
talos_suffix =        { path = "../talos_suffix" }
talos_common_utils =  { path = "../talos_common_utils" }
talos_rdkafka_utils = { path = "../talos_rdkafka_utils" }


[dev-dependencies]
serial_test = "2.0.0"
