[package]
name = "cohort_sdk_js"
version = "0.0.1"
edition = "2021"


[lib]
crate-type = ["cdylib"]
[dependencies]
# lib for napi bindings
napi = { version = "2.10.3", features = [
    "async",
    "tokio_rt",
    "napi8",
    "chrono_date",
    "serde-json",
] }
napi-derive = "2.9.3"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
# Logging
log = { version = "0.4", features = [
    "kv_unstable",
    "std",
    "kv_unstable_serde",
] }

# db migrations
#refinery = {version="0.8", features=["tokio-postgres"]}
# crate depencies
cohort_sdk = { path = "../cohort_sdk" }
tokio = { workspace = true, features = ["full"] }
talos_cohort_replicator = { path = "../../packages/talos_cohort_replicator" }
talos_certifier = { path = "../talos_certifier" }
talos_certifier_adapters = { path = "../../packages/talos_certifier_adapters" }
talos_rdkafka_utils = { path = "../talos_rdkafka_utils" }

async-trait = "0.1.72"
# rdkafka = { version = "0.34.0", features = ["sasl"] }
# rdkafka-sys = { version = "4.3.0" }

[build-dependencies]
napi-build = "2.0.1"

#[dev-dependencies.cargo-husky]
#version = "1"
#default-features = false # Disable features which are enabled by default
#features = ["user-hooks"]
