[package]
name = "cohort_sdk_js"
version = "0.2.42"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "2.0.1"

[dependencies]
# lib for napi bindings
napi = { version = "2.10.3", features = [
    "async",
    "tokio_rt",
    "napi8",
    "chrono_date",
    "serde-json",
] }
napi-build = "=2.1.3" # pinned to use rustc 75
zerofrom = { version = "=0.1.5" }
litemap = { version = "=0.7.4" }
napi-derive = "2.9.3"
thiserror = "2.0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
chrono = { version = "0.4.19", features = ["serde"] }

tokio = { workspace = true, features = ["full"] }

cohort_sdk = { path = "../cohort_sdk", version = "0.2.42" }
talos_agent = { path = "../talos_agent", version = "0.2.42" }
talos_cohort_replicator = { path = "../talos_cohort_replicator", version = "0.2.42" }
talos_certifier = { path = "../talos_certifier", version = "0.2.42" }
talos_certifier_adapters = { path = "../talos_certifier_adapters", version = "0.2.42" }
talos_rdkafka_utils = { path = "../talos_rdkafka_utils", version = "0.2.42" }

async-trait = "0.1.72"
