[package]
name = "talos_agent"
version = "0.0.1"
edition = "2021"

[dependencies]

async-trait =   { workspace = true }
env_logger =    { workspace = true }
log =           { workspace = true }
rdkafka =       { version = "0.29.0", features = ["sasl"] }
rdkafka-sys =   { version = "4.3.0" }
serde =         { workspace = true }
serde_json =    { workspace = true }
strum =         { version = "0.24", features = ["derive"] }
tokio =         { workspace = true, features = ["full"] }
uuid =          { version = "1.2.2", features = ["v4"] }
time =          { workspace = true }











