[package]
name = "talos_agent"
version = "0.3.13-dev"
edition = "2021"

[dependencies]

async-trait = { workspace = true }
multimap = { version = "0.10.0" }
rdkafka = { version = "0.34.0", features = ["sasl"] }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { version = "0.27.1", features = ["derive"] }
thiserror = { version = "2.0.11" }

# Tracing dependencies
#   We will move telemetry dependencies to the workspace once we adapt all projects. Currenly only SDK uses them.
opentelemetry = { version = "0.28.0", default-features = false, features = [
    "trace",
] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-opentelemetry = { version = "0.29.0" }
# The end of tracing dependencies

time = { workspace = true }
tokio = { workspace = true, features = ["full"] }
uuid = { version = "1.4.1", features = ["v4"] }

# TODO: GK - temporary pinning of transient packages for MSRB 1.75
toml = { workspace = true }
toml_edit = { workspace = true }
toml_datetime = { workspace = true }
toml_parser = { workspace = true }
toml_writer = { workspace = true }

talos_rdkafka_utils = { path = "../talos_rdkafka_utils", version = "0.3.13-dev" }
talos_common_utils = { path = "../talos_common_utils", version = "0.3.13-dev" }

[dev-dependencies]
mockall = { version = "0.11.3" }
tokio-test = { version = "0.4.2" }
