[package]
name = "talos_agent"
version = "0.0.1"
edition = "2021"

[dependencies]

async-trait =   { workspace = true }
env_logger =    { workspace = true }
log =           { workspace = true }
multimap =      { version = "0.9.0" }
rdkafka =       { version = "0.33.2", features = ["sasl"] }
rdkafka-sys =   { version = "4.3.0" }
serde =         { workspace = true }
serde_json =    { workspace = true }
strum =         { version = "0.25", features = ["derive"] }
thiserror =     { version = "1.0.31" }
time =          { version = "0.3.17" }
tokio =         { workspace = true, features = ["full"] }
uuid =          { version = "1.2.2", features = ["v4"] }

talos_rdkafka_utils = { path = "../talos_rdkafka_utils" }

[dev-dependencies]
mockall =       { version = "0.11.3" }
tokio-test =    { version = "0.4.2" }
