[package]
name = "suffix"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
# Logging
log = { workspace = true }
env_logger = { workspace = true }

# Test
mockall = "0.11.0"

# Error
thiserror = "1.0.31"

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.4"

[[bench]]
name = "suffix"
harness = false
