[package]
name = "talos_suffix"
version = "0.2.58"
edition = "2021"
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Suffix implementations for Talos Certifier and Replicator"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

######### patches for build problems with rust 75
zerovec = { version = "=0.10.4" }
zerofrom= { version = "=0.1.5" }
icu_properties_data = { version = "=1.5.0" }
icu_locid_transform = { version = "=1.5.0" }
icu_normalizer = { version = "=1.5.0" }
icu_properties = { version = "=1.5.1" }
icu_provider = { version = "=1.5.0" }
icu_locid = { version = "=1.5.0" }
icu_collections = { version = "=1.5.0" }
icu_provider_macros = { version = "=1.5.0" }
icu_locid_transform_data = { version = "=1.5.0" }
yoke = { version = "=0.7.5"}
litemap = { version = "=0.7.4" }
########################################################

# Logging
#log = { workspace = true }
#env_logger = { workspace = true }

tracing =                   { version = "0.1.41", features = [ "log" ] }
opentelemetry_api =         { version = "0.20.0", features = ["metrics"] }
opentelemetry =             { version = "0.28.0", default-features = false, features = ["trace"]  }
opentelemetry_sdk =         { version = "0.28.0", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-otlp =        { version = "0.28.0", features = [ "trace", "grpc-tonic" ] }
opentelemetry-stdout =      { version = "0.28.0", features = [ "trace" ] }

# Test
mockall = "0.11.0"

# Error
thiserror = "1.0.31"

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.4"

[[bench]]
name = "suffix"
harness = false
