[package]
name = "talos_suffix"
version = "0.2.56-dev"
edition = "2021"
license = "MIT"
homepage = "https://github.com/kindredgroup/talos"
repository = "https://github.com/kindredgroup/talos"
readme = "README.md"
description = "Suffix implementations for Talos Certifier and Replicator"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
zerovec = { version = "=0.10.4" }
# Logging
#log = { workspace = true }
#env_logger = { workspace = true }

tracing =                   { version = "0.1.41", features = [ "log" ] }
opentelemetry_api =         { version = "0.20.0", features = ["metrics"] }
opentelemetry =             { version = "0.28.0", default-features = false, features = ["trace"]  }
opentelemetry_sdk =         { version = "0.28.0", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-otlp =        { version = "0.28.0", features = [ "trace", "grpc-tonic" ] }
opentelemetry-stdout =      { version = "0.28.0", features = [ "trace" ] }

# Test
mockall = "0.11.0"

# Error
thiserror = "1.0.31"

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.4"

[[bench]]
name = "suffix"
harness = false
