name: build

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
            - run: bin/ubuntu-setup.sh
            - run: rustup component add rustfmt clippy
            - name: cargo build
              run: cargo build
            - run: bin/pre-commit-checks.sh
