name: build

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
            - run: scripts/ubuntu-setup.sh
            - run: rustup component add rustfmt clippy
            - run: cargo clean
            - name: cargo build
              run: cargo build --release
            - run: scripts/pre-commit-checks.sh
